version: '3'
services:
  nginx:
    image: registry.rebrainme.com/devops_users_repos/5267/dkr-30-voting/nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/
    restart: always
    networks:
      - proxy
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.voting.rule=Host(`voting.51.250.27.106.nip.io`, `voting.89.169.163.117.nip.io`, `voting.89.169.166.159.nip.io`)
        - traefik.http.routers.voting.entrypoints=web
        - traefik.http.routers.voting.service=nginx
        - traefik.http.services.voting.loadbalancer.server.port=80 
  voting:
    image: registry.rebrainme.com/devops_users_repos/5267/dkr-30-voting/voting:latest
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=voting
      - DB_PASSWORD=voting
      - DB_DATABASE=voting
    depends_on:
      - mysql
      - redis
    restart: always
    deploy:
    networks:
      - proxy
    hostname: voting

  mysql:
    image: registry.rebrainme.com/devops_users_repos/5267/dkr-30-voting/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=voting
      - MYSQL_USER=voting
      - MYSQL_PASSWORD=voting
    restart: always
    volumes:
      - /mnt/mysql:/var/lib/mysql
    networks:
      - proxy

  redis:
    image: registry.rebrainme.com/devops_users_repos/5267/dkr-30-voting/redis:alpine
    restart: always
    networks:
      - proxy

networks:
  proxy:
    driver: overlay
    attachable: true

