services:

  nginx:
    ports:
    - "80:80"
    image: registry.rebrainme.com/devops_users_repos/5267/dkr-30-voting/nginx:stable-alpine
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./:/var/www/html/
    depends_on:
    - voting
    restart: unless-stopped
    deploy:
      replicas: 2

  voting:
    image: registry.rebrainme.com/devops_users_repos/5267/dkr-30-voting/voting:latest
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=voting
      - DB_PASSWORD=voting
      - DB_DATABASE=voting
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    ports:
      - "9000:9000"
    hostname: voting

  mysql:
    image: registry.rebrainme.com/devops_users_repos/5267/dkr-30-voting/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=voting
      - MYSQL_USER=voting
      - MYSQL_PASSWORD=voting
    restart: unless-stopped
    ports:
      - "3306:3306"

  redis:
   image: registry.rebrainme.com/devops_users_repos/5267/dkr-30-voting/redis:alpine
   ports:
      - "6379:6379"
