services:

  nginx:
    ports:
    - "20000:80"
    image: nginx:stable-alpine
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./:/var/www/html/
    depends_on:
    - voting
    restart: unless-stopped
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx.access

  voting:
    build: .
    image: voting:latest
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=voting
      - DB_PASSWORD=voting
      - DB_DATABASE=voting
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    ports:
      - "9000:9000"
    hostname: voting
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: voting.access

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=voting
      - MYSQL_USER=voting
      - MYSQL_PASSWORD=voting
    restart: unless-stopped
    ports:
      - "3306:3306"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: mysql.access

  redis:
   image: redis:alpine
   ports:
      - "6379:6379"
   logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: redis.access

  fluentd:
    build: ./fluentd/
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:8.14.2
    environment:
       - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
       - discovery.type=single-node
       - ELASTIC_PASSWORD=#enter here password
       - xpack.license.self_generated.type=basic
       - path.data=/usr/share/elasticsearch/data
       - bootstrap.memory_lock=true
       
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:8.14.2
    environment:
      - KIBANA_SECURITY_PROVIDERS=modern
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
