version: '3'
services:
  nginx:
    image: registry.rebrainme.com/devops_users_repos/5267/dkr-30-voting/nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/
    restart: always
    networks:
      - proxy
    deploy:
      replicas: 3
      labels:
        - traefik.enable=true
        - traefik.http.routers.voting1.rule=Host(`voting.158.160.52.24.nip.io`)
        - traefik.http.routers.voting1.entrypoints=web
        - traefik.http.routers.voting1.service=nginx
        - traefik.http.services.voting1.loadbalancer.server.port=80 

        - traefik.http.routers.voting2.rule=Host(`voting.158.160.125.61.nip.io`)
        - traefik.http.routers.voting2.entrypoints=web
        - traefik.http.routers.voting2.service=nginx
        - traefik.http.services.voting2.loadbalancer.server.port=80

        - traefik.http.routers.voting3.rule=Host(`voting.158.160.120.168.nip.io`)
        - traefik.http.routers.voting3.entrypoints=web
        - traefik.http.routers.voting3.service=nginx
        - traefik.http.services.voting3.loadbalancer.server.port=80

  voting:
    image: registry.rebrainme.com/devops_users_repos/5267/dkr-30-voting/voting:latest
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=voting
      - DB_PASSWORD=voting
      - DB_DATABASE=voting
    depends_on:
      - mysql
      - redis
    restart: always
    deploy:
    networks:
      - proxy

  mysql:
    image: registry.rebrainme.com/devops_users_repos/5267/dkr-30-voting/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=voting
      - MYSQL_USER=voting
      - MYSQL_PASSWORD=voting
    restart: always
    ports:
      - "3306:3306"
    networks:
      - proxy

  redis:
    image: registry.rebrainme.com/devops_users_repos/5267/dkr-30-voting/redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - proxy

networks:
  proxy:
    driver: overlay
    attachable: true
