services:

  nginx:
    ports:
    - "20000:80"
    image: nginx:stable-alpine
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./:/var/www/html/
    depends_on:
    - voting
    restart: unless-stopped

  voting:
    build: .
    image: voting:latest
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=voting
      - DB_PASSWORD=voting
      - DB_DATABASE=voting
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    ports:
      - "9000:9000"
    hostname: voting
    logging:
      driver: "fluentd"

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=voting
      - MYSQL_USER=voting
      - MYSQL_PASSWORD=voting
    restart: unless-stopped
    ports:
      - "3306:3306"
    logging:
      driver: "fluentd"


  redis:
   image: redis:alpine
   ports:
      - "6379:6379"
   logging:
      driver: "fluentd"


  fluentd:
    image: fluent/fluentd:v1.17-1
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:7.17.22
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped

  kibana:
    image: kibana:7.17.22
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped
