version: '3'
services:
  nginx:
    image: registry.rebrainme.com/devops_users_repos/5267/dkr-30-voting/nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - voting
    restart: always
    deploy:
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nginx.rule=Host(voting.89.169.175.69.nip.io, voting.89.169.166.181.nip.io, voting.89.169.173.211.nip.io)"
        - "traefik.http.services.nginx.entrypoints=web"
        - "traefik.http.services.nginx.loadbalancer.server.port=80"
        - "traefik.http.routers.nginx.rule=Path(`/`)"
    networks:
      - prox
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx.access

  voting:
    image: registry.rebrainme.com/devops_users_repos/5267/dkr-30-voting/voting:latest
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=voting
      - DB_PASSWORD=voting
      - DB_DATABASE=voting
    depends_on:
      - mysql
      - redis
    restart: always
    hostname: voting
    deploy:
      replicas: 1
    networks:
      - prox
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: voting.access

  mysql:
    image: registry.rebrainme.com/devops_users_repos/5267/dkr-30-voting/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=voting
      - MYSQL_USER=voting
      - MYSQL_PASSWORD=voting
    restart: always
    networks:
      - prox
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: mysql.access

  redis:
    image: registry.rebrainme.com/devops_users_repos/5267/dkr-30-voting/redis:alpine
    restart: always
    networks:
      - prox
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: redis.access

networks:
  prox:
    driver: overlay
    attachable: true
