version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.1
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - discovery.seed_hosts=elasticsearch
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - /mnt:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
    networks:
      - proxy

  fluentd:
    image: fluent/fluentd:v0.12-debian
    volumes:
      - ./fluentd/conf:/fluentd/etc
    deploy:
      mode: global
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - proxy

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - KIBANA_AUTH_TYPE=basic
      - KIBANA_AUTH_REALM=Kibana Realm
      - KIBANA_AUTH_USERNAME=rebrainme
      - KIBANA_AUTH_PASSWORD=DockerRocks!
    ports:
      - "80:5601"
    deploy:
      mode: global
    labels:
      - traefik.enable=true
      - traefik.http.routers.kibana.rule=Host(kibana.89.169.175.177.nip.io)
      - traefik.http.routers.kibana.entrypoints=web
      - traefik.http.routers.kibana.service=kibana
    networks:
      - proxy
  
networks:
  proxy:
    driver: overlay
