version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.17.23
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - discovery.seed_hosts=elasticsearch
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - /mnt:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - proxy

  fluentd:
    image: fluent/fluentd:v0.12-debian
    volumes:
      - ./fluentd/conf:/fluentd/etc
    deploy:
      mode: global
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - proxy

  kibana:
    image: kibana:7.17.23
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - KIBANA_AUTH_TYPE=basic
      - KIBANA_AUTH_REALM=Kibana Realm
      - KIBANA_AUTH_USERNAME=rebrainme
      - KIBANA_AUTH_PASSWORD=DockerRocks!
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana.rule=Host(kibana.89.169.175.177.nip.io)"
      - "traefik.http.services.kibana.entrypoints=web"
    networks:
      - proxy
  
networks:
  proxy:
    driver: overlay
