version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.15.0
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - discovery.type=single-node
      - discovery.seed_hosts=elasticsearch
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - /mnt:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - prox

  fluentd:
    image: fluent/fluentd:v0.12-debian
    volumes:
      - ./fluentd/conf:/fluentd/etc
    deploy:
      mode: global
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - prox

  kibana:
    image: kibana:8.15.0
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.kibana.rule=Host(kibana.89.169.175.69.nip.io)"
        - "traefik.http.services.kibana.entrypoints=web"
        - "traefik.http.routers.kibana.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=rebrainme:$2y$05$GULcAp5N4VtFT.9Yuk.s/ePoKV./cng1LhzEiWSklplyR5zrq4vZS"
        - "traefik.http.services.kibana.loadbalancer.server.port=5601"
    networks:
      - prox

networks:
  prox:
    driver: overlay
