version: '3'

services:
  traefik:
    image: traefik:v2.8
    command:
      - --providers.docker.swarmmode=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.email=bondar3nko.nikit@yandex.ru
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - proxy
networks:
  proxy:
    driver: overlay
    attachable: true
