version: '3'

services:
  traefik:
    image: traefik:v2.8
    command:
      - --providers.docker.swarmmode=true
      - --entrypoints.web.address=:80
      - --api.insecure=true
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.email=bondar3nko.nikit@yandex.ru
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: always
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - prox
networks:
  prox:
    driver: overlay
    attachable: true
